matrix:
  include:
  # GCC 9
  - os: linux
    dist: xenial
    sudo: required
    addons: &gcc9
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - pkg-config
        - ninja-build
        - cmake
        - gcc-9
        - g++-9
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
        - libglfw3-dev
#       - glslang-dev
#       - libbullet-dev
#       - libphysfs-dev
    language: cpp
    compiler: gcc
    env:
    - COMPILER=g++-9
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  # Clang 8
  - os: linux
    dist: xenial
    sudo: required
    addons: &clang8
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - pkg-config
        - ninja-build
        - cmake
        - g++-8
        - clang-8
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
        - libglfw3-dev
#       - glslang-dev
#       - libbullet-dev
#       - libphysfs-dev
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-8
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - sudo apt-get update -qq
  # XCode 11.3
  - os: osx
    osx_image: xcode11.3
    sudo: required
    addons:
      homebrew:
        taps:
        - homebrew/cask
        casks:
        - apenngrace/vulkan/vulkan-sdk
        packages:
        - pkg-config
        - cmake
        - gcc
        - llvm
        - openal-soft
        - glfw
        - glslang
        - bullet
        - physfs
      update: true
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - export PATH="/usr/local/opt/llvm/bin:$PATH"

script:
- mkdir Build && cd Build
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      ninja
    else
      cmake .. -G "Xcode" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      xcodebuild -target Acid -configuration $BUILD_TYPE
    fi
